"""
Nexus Shield AI - Report

Builds the human-readable report shown in the UI and offered as a download.
"""

from __future__ import annotations

from datetime import datetime


def build_report_text(url: str, score: int, status: str, explained_issues: list[dict]) -> str:
    lines = [
        "Nexus Shield Report",
        "====================",
        "",
        f"Website: {url}",
        f"Date: {datetime.now().strftime('%B %d, %Y')}",
        f"Security Score: {score}/100 ({status})",
        "",
        f"Issues Found: {len(explained_issues)}",
        "",
    ]

    if not explained_issues:
        lines.append("No issues found. Nice work keeping this site secure!")
    else:
        lines.append("Recommendations:")
        for idx, issue in enumerate(explained_issues, start=1):
            lines.append(f"{idx}. {issue['explanation']}")
            lines.append(f"   Fix: {issue['fix']}")
            lines.append("")

    lines.append("Generated by Nexus Shield AI — a passive, read-only security scan.")
    lines.append("This report is informational and is not a substitute for a professional security audit.")
    return "\n".join(lines)
